#!/usr/bin/env python
import sys
import subprocess

if __name__ == '__main__':
    # Run pytest in the repo root
    result = subprocess.run([sys.executable, '-m', 'pytest', '-q'], stdout=sys.stdout, stderr=sys.stderr)
    sys.exit(result.returncode)
